title:              Portfolio
email:              ag2146@scarletmail.rutgers.edu
description:        Transforming raw data into actionable insights through SQL, Excel, and Tableau
author:             Ani Guliashvili
baseurl:            ""
url:                "https://datadriven.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username: a.gullli 
linkedin_username: Aniguliashvili

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
